-- MySQL Script generated by MySQL Workbench
-- Sun Feb 13 22:48:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`RECHARGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RECHARGE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RECHARGE` (
  `idRecharge` INT NOT NULL,
  `nomRecharge` VARCHAR(255) NOT NULL,
  `puissanceRecharge` VARCHAR(45) NULL,
  `typeCourant` VARCHAR(45) NULL,
  `accesRecharge` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecharge`));


-- -----------------------------------------------------
-- Table `mydb`.`UTILISATEUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UTILISATEUR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UTILISATEUR` (
  `idUtilisateur` INT NOT NULL,
  `profilUtilisateur` VARCHAR(255) NULL,
  `nomUtilisateur` VARCHAR(32) NOT NULL,
  `prenomUtilisateur` VARCHAR(32) NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(45) NULL,
  `motDePasse` VARCHAR(45) NULL,
  `montant` INT NULL,
  `pointsFidelite` INT NULL,
  PRIMARY KEY (`idUtilisateur`));


-- -----------------------------------------------------
-- Table `mydb`.`BORNE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BORNE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BORNE` (
  `idBorne` INT NOT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NOT NULL,
  `accesBorne` VARCHAR(30) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idBorne`));


-- -----------------------------------------------------
-- Table `mydb`.`LIAISON_BORNE_RECHARGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LIAISON_BORNE_RECHARGE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LIAISON_BORNE_RECHARGE` (
  `idBorne` INT NOT NULL,
  `idRecharge` INT NOT NULL,
  PRIMARY KEY (`idBorne`, `idRecharge`),
  INDEX `idRecharge_idx` (`idRecharge` ASC) VISIBLE,
  CONSTRAINT `fkIdBorneRecharge`
    FOREIGN KEY (`idBorne`)
    REFERENCES `mydb`.`BORNE` (`idBorne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkBorneRecharge`
    FOREIGN KEY (`idRecharge`)
    REFERENCES `mydb`.`RECHARGE` (`idRecharge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`TECHNICIEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TECHNICIEN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TECHNICIEN` (
  `idTechnicien` INT NOT NULL,
  `nomTechnicien` VARCHAR(255) NOT NULL,
  `prenomTechnicien` VARCHAR(45) NULL,
  PRIMARY KEY (`idTechnicien`));


-- -----------------------------------------------------
-- Table `mydb`.`LIAISON_UTILISATEUR_BORNE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LIAISON_UTILISATEUR_BORNE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LIAISON_UTILISATEUR_BORNE` (
  `idUtilisateur` INT NOT NULL,
  `idBorne` INT NOT NULL,
  `idTechnicien` INT NOT NULL,
  `prixPose` DOUBLE NULL,
  `datePose` DATE NULL,
  PRIMARY KEY (`idUtilisateur`, `idBorne`, `idTechnicien`),
  INDEX `fkBorne_idx` (`idBorne` ASC) VISIBLE,
  INDEX `fkTechnicien_idx` (`idTechnicien` ASC) VISIBLE,
  CONSTRAINT `fkUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`UTILISATEUR` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkBorne`
    FOREIGN KEY (`idBorne`)
    REFERENCES `mydb`.`BORNE` (`idBorne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkTechnicien`
    FOREIGN KEY (`idTechnicien`)
    REFERENCES `mydb`.`TECHNICIEN` (`idTechnicien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
